version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  bot:
    build: ./kernel
    env_file:
      - ./kernel/.env
    volumes:
      - ./kernel:/app
    depends_on:
      - redis
