"""создала новое поле для напоминаний

Revision ID: 21876f939243
Revises: 89a022cb6112
Create Date: 2024-07-03 20:29:03.659579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21876f939243'
down_revision: Union[str, None] = '89a022cb6112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('name', sa.Text(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'name')
    # ### end Alembic commands ###
