"""удалила not null

Revision ID: 23cc0cd5af2e
Revises: 5ecef6a0a6d9
Create Date: 2024-07-05 13:59:42.060901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cc0cd5af2e'
down_revision: Union[str, None] = '5ecef6a0a6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminders', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('reminders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
