"""поменяла вторичный ключ у owner_id

Revision ID: 454af05e1b8d
Revises: 23cc0cd5af2e
Create Date: 2024-07-14 17:51:29.662632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454af05e1b8d'
down_revision: Union[str, None] = '23cc0cd5af2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'users', ['owner_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
